# -*- coding: utf-8 -*-
# 中文注释：名称来自 CATS FixArmature 的最终标准骨名，而不是原始 PMX 名。
# CATS 默认会把扭转骨改为 zArmTwist/zHandTwist，但对应顶点组通常仍保留无 z 名称，
# 所以吸附表和顶点组重命名表必须分别覆盖两种结果。
# 列表方向：[CATS 修复后来源骨/顶点组, 潜兵目标骨]。

snap_bone_fixed_name_list = [
    ['Hips', 'hips'],
    ['Spine', 'spine1'],
    ['Chest', 'spine2'],
    ['Upper Chest', 'chest'],
    ['Chest', 'chest'],  # 没有 Upper Chest 时的吸附回退。
    ['Neck', 'neck'],
    ['Head', 'head'],

    ['Left shoulder', 'l_clavicle'],
    ['Left arm', 'l_shoulder'],
    ['zArmTwist_L', 'l_shoulder_twist'],
    ['ArmTwist_L', 'l_shoulder_twist'],
    ['Left elbow', 'l_elbow'],
    ['zHandTwist_L', 'l_hand_twist'],
    ['HandTwist_L', 'l_hand_twist'],
    ['Left wrist', 'l_hand'],
    ['Right shoulder', 'r_clavicle'],
    ['Right arm', 'r_shoulder'],
    ['zArmTwist_R', 'r_shoulder_twist'],
    ['ArmTwist_R', 'r_shoulder_twist'],
    ['Right elbow', 'r_elbow'],
    ['zHandTwist_R', 'r_hand_twist'],
    ['HandTwist_R', 'r_hand_twist'],
    ['Right wrist', 'r_hand'],

    ['Left leg', 'l_thigh'],
    ['Left knee', 'l_knee'],
    ['Left ankle', 'l_foot'],
    ['Left toe', 'l_ball'],
    ['Right leg', 'r_thigh'],
    ['Right knee', 'r_knee'],
    ['Right ankle', 'r_foot'],
    ['Right toe', 'r_ball'],

    ['Thumb0_L', 'l_thumb_finger1'],
    ['Thumb1_L', 'l_thumb_finger2'],
    ['Thumb2_L', 'l_thumb_finger3'],
    ['IndexFinger1_L', 'l_index_finger1'],
    ['IndexFinger2_L', 'l_index_finger2'],
    ['IndexFinger3_L', 'l_index_finger3'],
    ['MiddleFinger1_L', 'l_middle_finger1'],
    ['MiddleFinger2_L', 'l_middle_finger2'],
    ['MiddleFinger3_L', 'l_middle_finger3'],
    ['RingFinger1_L', 'l_ring_finger1'],
    ['RingFinger2_L', 'l_ring_finger2'],
    ['RingFinger3_L', 'l_ring_finger3'],
    ['LittleFinger1_L', 'l_pinky_finger1'],
    ['LittleFinger2_L', 'l_pinky_finger2'],
    ['LittleFinger3_L', 'l_pinky_finger3'],
    ['Thumb0_R', 'r_thumb_finger1'],
    ['Thumb1_R', 'r_thumb_finger2'],
    ['Thumb2_R', 'r_thumb_finger3'],
    ['IndexFinger1_R', 'r_index_finger1'],
    ['IndexFinger2_R', 'r_index_finger2'],
    ['IndexFinger3_R', 'r_index_finger3'],
    ['MiddleFinger1_R', 'r_middle_finger1'],
    ['MiddleFinger2_R', 'r_middle_finger2'],
    ['MiddleFinger3_R', 'r_middle_finger3'],
    ['RingFinger1_R', 'r_ring_finger1'],
    ['RingFinger2_R', 'r_ring_finger2'],
    ['RingFinger3_R', 'r_ring_finger3'],
    ['LittleFinger1_R', 'r_pinky_finger1'],
    ['LittleFinger2_R', 'r_pinky_finger2'],
    ['LittleFinger3_R', 'r_pinky_finger3'],
]


rename_vg_fixed_name_list = [
    ['Hips', 'hips'],
    ['Spine', 'spine1'],
    # CATS 的 Chest/Upper Chest 都是胸部权重；不把同一组强拆成 spine2 + chest。
    ['Chest', 'chest'],
    ['Upper Chest', 'chest'],
    ['Neck', 'neck'],
    ['Head', 'head'],

    ['Left shoulder', 'l_clavicle'],
    ['Left arm', 'l_shoulder'],
    ['ArmTwist_L', 'l_shoulder_twist'],
    ['zArmTwist_L', 'l_shoulder_twist'],
    ['Left elbow', 'l_elbow'],
    ['HandTwist_L', 'l_hand_twist'],
    ['zHandTwist_L', 'l_hand_twist'],
    ['Left wrist', 'l_hand'],
    ['Right shoulder', 'r_clavicle'],
    ['Right arm', 'r_shoulder'],
    ['ArmTwist_R', 'r_shoulder_twist'],
    ['zArmTwist_R', 'r_shoulder_twist'],
    ['Right elbow', 'r_elbow'],
    ['HandTwist_R', 'r_hand_twist'],
    ['zHandTwist_R', 'r_hand_twist'],
    ['Right wrist', 'r_hand'],

    ['Left leg', 'l_thigh'],
    ['Left knee', 'l_knee'],
    ['Left ankle', 'l_foot'],
    ['Left toe', 'l_ball'],
    ['Right leg', 'r_thigh'],
    ['Right knee', 'r_knee'],
    ['Right ankle', 'r_foot'],
    ['Right toe', 'r_ball'],

    ['Thumb0_L', 'l_thumb_finger1'],
    ['Thumb1_L', 'l_thumb_finger2'],
    ['Thumb2_L', 'l_thumb_finger3'],
    ['IndexFinger1_L', 'l_index_finger1'],
    ['IndexFinger2_L', 'l_index_finger2'],
    ['IndexFinger3_L', 'l_index_finger3'],
    ['MiddleFinger1_L', 'l_middle_finger1'],
    ['MiddleFinger2_L', 'l_middle_finger2'],
    ['MiddleFinger3_L', 'l_middle_finger3'],
    ['RingFinger1_L', 'l_ring_finger1'],
    ['RingFinger2_L', 'l_ring_finger2'],
    ['RingFinger3_L', 'l_ring_finger3'],
    ['LittleFinger1_L', 'l_pinky_finger1'],
    ['LittleFinger2_L', 'l_pinky_finger2'],
    ['LittleFinger3_L', 'l_pinky_finger3'],
    ['Thumb0_R', 'r_thumb_finger1'],
    ['Thumb1_R', 'r_thumb_finger2'],
    ['Thumb2_R', 'r_thumb_finger3'],
    ['IndexFinger1_R', 'r_index_finger1'],
    ['IndexFinger2_R', 'r_index_finger2'],
    ['IndexFinger3_R', 'r_index_finger3'],
    ['MiddleFinger1_R', 'r_middle_finger1'],
    ['MiddleFinger2_R', 'r_middle_finger2'],
    ['MiddleFinger3_R', 'r_middle_finger3'],
    ['RingFinger1_R', 'r_ring_finger1'],
    ['RingFinger2_R', 'r_ring_finger2'],
    ['RingFinger3_R', 'r_ring_finger3'],
    ['LittleFinger1_R', 'r_pinky_finger1'],
    ['LittleFinger2_R', 'r_pinky_finger2'],
    ['LittleFinger3_R', 'r_pinky_finger3'],
]
